name: drawsync_desktop
description: DrawSync desktop receiver/viewer
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_models:
    path: ../../packages/shared_models
  shared_protocol:
    path: ../../packages/shared_protocol
  shared_canvas:
    path: ../../packages/shared_canvas

flutter:
  uses-material-design: true
