
### Download a song (success)
POST http://localhost:8080/api/songs/download
Content-Type: application/json

{
    "videoId": "mbsmsi7l3r4"
}

### Download same song again (duplicate check)
POST http://localhost:8080/api/songs/download
Content-Type: application/json

{
    "videoId": "UBUNrFtufWo"
}

### Download song (missing videoId)
POST http://localhost:8080/api/songs/download
Content-Type: application/json

{
}

### Download song (empty videoId)
POST http://localhost:8080/api/songs/download
Content-Type: application/json

{
    "videoId": "   "
}
