name: shared_canvas
description: Canvas rendering widgets for DrawSync
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_models:
    path: ../shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
