analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_final_fields
    - prefer_const_constructors
    - prefer_const_declarations
    - annotate_overrides
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_this
